# because github actions are shit, we need to combine every workflow in one file in order to be able to have jobs depend correctly on other jobs

name: CI / CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  ci:
    name: Unittest ${{ matrix.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-24.04, windows-latest ]
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Debug env
        run: env
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      - name: Install fastapi_webpush_endpoint
        run: pip install -e '.[development]'
      - name: Lint with flake8
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Type check with pyright
        run: pyright
      - name: Run tests
        run: python -m unittest

  cd:
    needs: [ ci ]
    if: github.ref == 'refs/heads/main'
    name: Upload release to PyPI
    runs-on: ubuntu-24.04
    environment:
      name: pypi
      url: https://pypi.org/u/eskildsf
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: python -m pip install --upgrade pip build
      - name: Build fastapi_webpush_endpoint
        run: python -m build --sdist -o dist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1